/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DebtsIndexImport } from './routes/debts/index'
import { Route as DebtsCreateImport } from './routes/debts/create'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DebtsIndexRoute = DebtsIndexImport.update({
  id: '/debts/',
  path: '/debts/',
  getParentRoute: () => rootRoute,
} as any)

const DebtsCreateRoute = DebtsCreateImport.update({
  id: '/debts/create',
  path: '/debts/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/debts/create': {
      id: '/debts/create'
      path: '/debts/create'
      fullPath: '/debts/create'
      preLoaderRoute: typeof DebtsCreateImport
      parentRoute: typeof rootRoute
    }
    '/debts/': {
      id: '/debts/'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debts/create': typeof DebtsCreateRoute
  '/debts': typeof DebtsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debts/create': typeof DebtsCreateRoute
  '/debts': typeof DebtsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/debts/create': typeof DebtsCreateRoute
  '/debts/': typeof DebtsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/debts/create' | '/debts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/debts/create' | '/debts'
  id: '__root__' | '/' | '/debts/create' | '/debts/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebtsCreateRoute: typeof DebtsCreateRoute
  DebtsIndexRoute: typeof DebtsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebtsCreateRoute: DebtsCreateRoute,
  DebtsIndexRoute: DebtsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/debts/create",
        "/debts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/debts/create": {
      "filePath": "debts/create.tsx"
    },
    "/debts/": {
      "filePath": "debts/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
